version: "3.8"

services:
  portfolio-db:
    image: postgres:15-alpine
    container_name: portfolio-db
    restart: always
    ports:
      - "5433:5432" # Using 5433 to avoid conflict with wheplay
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: portfolio
    volumes:
      - portfolio-data:/var/lib/postgresql/data

volumes:
  portfolio-data:
