import { PrismaClient } from "@prisma/client";

const prisma = new PrismaClient();

async function main() {
  // Delete existing data
  await prisma.project.deleteMany();

  const projects = [
    {
      title: "Marc Stämpfli UI Design",
      slug: "marc-stampfli-ui-design",
      description: "UI/UX design for personal portfolio website",
      content:
        "A modern and intuitive UI design for my personal portfolio website, focusing on user experience and visual appeal.",
      category: "UI Designs",
      tags: ["UI/UX", "Web Design"],
      tech_stack: ["Figma"],
      images: ["project-marcstampfli-ui.jpg"],
      client: "Marc Stämpfli",
      status: "published",
      order: 0,
      created_at: new Date("2021-04-05"),
      updated_at: new Date("2021-04-05"),
    },
    {
      title: "Craigslist Redesign",
      slug: "craigslist-redesign",
      description: "Modern UI redesign concept for Craigslist",
      content:
        "A modern redesign concept for Craigslist, focusing on improving usability while maintaining familiarity.",
      category: "UI Designs",
      tags: ["UI/UX", "Web Design"],
      tech_stack: ["Figma"],
      images: ["project-craigslist-ui.jpg", "project-craigslist-ui2.jpg"],
      client: "Craigslist",
      status: "published",
      order: 1,
      created_at: new Date("2021-04-05"),
      updated_at: new Date("2021-04-05"),
    },
    {
      title: "Breezy Brands UI Design",
      slug: "breezy-brands-ui-design",
      description: "UI/UX design for Breezy Brands website",
      content:
        "A comprehensive UI/UX design project for Breezy Brands' digital platform, focusing on brand consistency and modern design principles.",
      category: "UI Designs",
      tags: ["UI/UX", "Web Design"],
      tech_stack: ["Adobe XD"],
      images: ["project-breezybrands.jpg"],
      client: "Breezy Brands",
      status: "published",
      order: 2,
      created_at: new Date("2021-07-09"),
      updated_at: new Date("2021-07-09"),
    },
    {
      title: "Roma UI Design",
      slug: "roma-ui-design",
      description: "UI/UX design for ROMA website",
      content:
        "A modern and professional UI design for ROMA's corporate website, emphasizing brand identity and user experience.",
      category: "UI Designs",
      tags: ["UI/UX", "Web Design"],
      tech_stack: ["Figma"],
      images: ["project-roma-ui.jpg", "project-roma-ui2.jpg"],
      client: "ROMA",
      status: "published",
      order: 4,
      created_at: new Date("2021-04-05"),
      updated_at: new Date("2021-04-05"),
    },
    {
      title: "Covid Tracker",
      slug: "covid-tracker",
      description: "Real-time COVID-19 statistics tracking application",
      content:
        "Interactive web application providing up-to-date COVID-19 statistics using external APIs and data visualization.",
      category: "Web Apps",
      tags: ["Web Development", "Data Visualization"],
      tech_stack: ["React", "API"],
      images: [
        "project-covidtracker-website4.jpg",
        "project-covidtracker-website.jpg",
        "project-covidtracker-website2.jpg",
        "project-covidtracker-website3.jpg",
      ],
      live_url: "https://covid-19-tracker-27c81.web.app/",
      client: "Personal Project",
      status: "published",
      order: 5,
      created_at: new Date("2021-04-03"),
      updated_at: new Date("2021-04-03"),
    },
    {
      title: "Tinder Clone",
      slug: "tinder-clone",
      description: "Tinder clone built with React and Firebase",
      content:
        "A full-featured Tinder clone showcasing real-time functionality and modern web development practices.",
      category: "Web Apps",
      tags: ["Web Development", "Clone"],
      tech_stack: ["React", "Firebase"],
      images: ["project-tinder-clone.jpg", "project-tinder-clone2.jpg"],
      live_url: "https://tinder-clone-8baa7.web.app/",
      client: "Personal Project",
      status: "published",
      order: 6,
      created_at: new Date("2021-04-03"),
      updated_at: new Date("2021-04-03"),
    },
    {
      title: "Hulu Clone",
      slug: "hulu-clone",
      description: "Hulu streaming platform clone",
      content:
        "A clone of the Hulu streaming platform featuring a modern UI and responsive design.",
      category: "Web Apps",
      tags: ["Web Development", "Clone"],
      tech_stack: ["React", "Firebase"],
      images: ["project-hulu-clone.jpg"],
      live_url: "https://hulu-clone-d0922.web.app/",
      client: "Personal Project",
      status: "published",
      order: 7,
      created_at: new Date("2021-04-03"),
      updated_at: new Date("2021-04-03"),
    },
    {
      title: "Amazon Clone",
      slug: "amazon-clone",
      description: "Amazon e-commerce platform clone with Stripe integration",
      content:
        "A comprehensive clone of Amazon's e-commerce platform featuring user authentication, product catalog, and Stripe payments.",
      category: "Web Apps",
      tags: ["Web Development", "E-commerce", "Clone"],
      tech_stack: ["React", "Firebase", "Stripe"],
      images: [
        "project-amazon-clone.jpg",
        "project-amazon-clone2.jpg",
        "project-amazon-clone3.jpg",
      ],
      live_url: "https://clone-666e1.web.app/",
      client: "Personal Project",
      status: "published",
      order: 8,
      created_at: new Date("2021-04-03"),
      updated_at: new Date("2021-04-03"),
    },
    {
      title: "Breezy Brands Website",
      slug: "breezy-brands-website",
      description: "Custom WordPress website for Breezy Brands",
      content:
        "A custom WordPress website featuring modern design, optimized performance, and responsive layout.",
      category: "Websites",
      tags: ["Web Development", "WordPress"],
      tech_stack: ["WordPress", "Custom Theme"],
      images: [
        "project-breezybrands.jpg",
        "project-breezybrands2.jpg",
        "project-breezybrands3.jpg",
      ],
      live_url: "https://breezybrands.com",
      client: "Breezy Brands",
      status: "published",
      order: 9,
      created_at: new Date("2021-07-09"),
      updated_at: new Date("2021-07-09"),
    },
    {
      title: "Softbox Studios Website",
      slug: "softbox-studios-website",
      description: "Website development for Softbox Studios",
      content:
        "A professional website showcasing Softbox Studios' portfolio and services.",
      category: "Websites",
      tags: ["Web Development"],
      tech_stack: ["Web Development"],
      images: [
        "project-softbox-website.jpg",
        "project-softbox-website2.jpg",
        "project-softbox-website3.jpg",
        "project-softbox-website4.jpg",
        "project-softbox-website5.jpg",
      ],
      client: "Softbox Studios",
      status: "published",
      order: 10,
      created_at: new Date("2021-04-02"),
      updated_at: new Date("2021-04-02"),
    },
    {
      title: "IOCL Website",
      slug: "iocl-website",
      description: "Website development for IOCL",
      content:
        "A corporate website development project for IOCL featuring modern design and functionality.",
      category: "Websites",
      tags: ["Web Development"],
      tech_stack: ["Web Development"],
      images: [
        "project-iocl-website.jpg",
        "project-iocl-website2.jpg",
        "project-iocl-website3.jpg",
      ],
      live_url: "http://www.iocltt.com/",
      client: "IOCL",
      status: "published",
      order: 11,
      created_at: new Date("2021-04-02"),
      updated_at: new Date("2021-04-02"),
    },
    {
      title: "TriniStars Website",
      slug: "trinistars-website",
      description: "WordPress website for TriniStars",
      content:
        "A WordPress website development project featuring custom modifications and responsive design.",
      category: "Websites",
      tags: ["WordPress", "Modified Theme"],
      tech_stack: ["WordPress"],
      images: [
        "project-trinistars-website.jpg",
        "project-trinistars-website2.jpg",
        "project-trinistars-website3.jpg",
      ],
      live_url: "http://trinistars.com/",
      client: "TriniStars",
      status: "published",
      order: 12,
      created_at: new Date("2021-04-05"),
      updated_at: new Date("2021-04-05"),
    },
    {
      title: "RL Photography Website",
      slug: "rl-photography-website",
      description: "Photography portfolio website",
      content:
        "A photography portfolio website showcasing professional work and services.",
      category: "Websites",
      tags: ["WordPress", "Modified Theme"],
      tech_stack: ["WordPress"],
      images: [
        "project-rlphoto-website.jpg",
        "project-rl-photo.jpg",
        "project-rlphoto-website2.jpg",
        "project-rlphoto-website3.jpg",
      ],
      live_url: "http://rainierlangephotography.com/",
      client: "RL Photography",
      status: "published",
      order: 13,
      created_at: new Date("2021-04-05"),
      updated_at: new Date("2021-04-05"),
    },
    {
      title: "Gypsea Soul Jewelry Website",
      slug: "gypsea-soul-jewelry-website",
      description: "E-commerce website for jewelry brand",
      content:
        "An e-commerce website for a jewelry brand featuring product catalog and secure payments.",
      category: "Websites",
      tags: ["WordPress", "E-commerce", "PayPal"],
      tech_stack: ["WordPress", "Modified Theme", "PayPal"],
      images: [
        "project-gypsea-website.jpg",
        "project-gypsea-website2.jpg",
        "project-gypsea-website3.jpg",
        "project-gypsea-website4.jpg",
        "project-gypsea-website5.jpg",
      ],
      live_url: "https://gypseasouljewelry.co/",
      client: "Gypsea Soul Jewelry",
      status: "published",
      order: 14,
      created_at: new Date("2021-04-02"),
      updated_at: new Date("2021-04-02"),
    },
    {
      title: "Lagoona Villa Website",
      slug: "lagoona-villa-website",
      description: "Website for luxury villa rental",
      content:
        "A luxury villa rental website showcasing property features and booking functionality.",
      category: "Websites",
      tags: ["WordPress"],
      tech_stack: ["WordPress"],
      images: [
        "project-lagoona-website.jpg",
        "project-lagoona-website2.jpg",
        "project-lagoona-website3.jpg",
        "project-lagoona-website4.jpg",
      ],
      live_url: "https://www.lagoonavilla.com/",
      client: "Lagoona Villa",
      status: "published",
      order: 15,
      created_at: new Date("2021-04-02"),
      updated_at: new Date("2021-04-02"),
    },
    {
      title: "GameKas Logo",
      slug: "gamekas-logo",
      description: "Logo design for gaming brand",
      content:
        "A modern logo design for a gaming brand focusing on brand identity.",
      category: "Logos",
      tags: ["Logo Design"],
      tech_stack: ["Photoshop"],
      images: ["project-gamekas-logo.jpg"],
      client: "GameKas",
      status: "published",
      order: 16,
      created_at: new Date("2021-04-03"),
      updated_at: new Date("2021-04-03"),
    },
    {
      title: "Gimmick Tees Logo",
      slug: "gimmick-tees-logo",
      description: "Logo design for t-shirt brand",
      content:
        "A creative logo design for a t-shirt brand emphasizing brand personality.",
      category: "Logos",
      tags: ["Logo Design"],
      tech_stack: ["Photoshop"],
      images: ["project-gt.jpg"],
      client: "Gimmick Tees",
      status: "published",
      order: 17,
      created_at: new Date("2021-04-02"),
      updated_at: new Date("2021-04-02"),
    },
    {
      title: "Irie Bites Digital Signage",
      slug: "irie-bites-digital-signage",
      description: "Digital menu board design",
      content:
        "A digital menu board design for a restaurant focusing on clarity and visual appeal.",
      category: "Digital Signage",
      tags: ["Digital Signage"],
      tech_stack: ["Photoshop"],
      images: ["project-iriebites-digitalsignage.jpg"],
      client: "Irie Bites",
      status: "published",
      order: 18,
      created_at: new Date("2021-04-03"),
      updated_at: new Date("2021-04-03"),
    },
    {
      title: "PAID Carwash Banner",
      slug: "paid-carwash-banner",
      description: "Banner design for car wash service",
      content: "An eye-catching banner design for a car wash service.",
      category: "Banners",
      tags: ["Banner Design"],
      tech_stack: ["Illustrator"],
      images: ["project-paidcarwash.jpg"],
      client: "PAID Carwash",
      status: "published",
      order: 19,
      created_at: new Date("2021-04-02"),
      updated_at: new Date("2021-04-02"),
    },
  ];

  for (const project of projects) {
    await prisma.project.create({
      data: project,
    });
  }

  console.log("Database has been seeded");
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
